# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9bc6346d8d763977acd41f0452c892edf75a9f2426617513e6d5b1d9d2250a9bde9c9641460f8a8f680e7605634c7b7566eee64e677a9597d3afaf7bc0d661e7

test:
  secret_key_base: 75446902cb77869de8a7288c31899718fc6536bb4079a5963b96d225e4a04ba3602d9095ebc0e3d302e6e0cff4a3ac5dafd0d2f64670b2dad94744f337b5eaf3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
